name: build-dev-repo

on:
  - push
 # schedule:
 #   - cron: '0 0 * * SUN' # Every Sunday at 00:00 UTC */

jobs:
  build:
    strategy:
      matrix:
          os:
            - ubuntu-latest
            - macos-latest
          ocaml-version:
#            - 4.09.1
#            - 4.08.1
            - 4.07.1

    runs-on: ${{ matrix.os }}

    env:
      TMPDIR: /tmp
      XDG_CACHE_HOME: /tmp/cache
      BAP_LOG_DIR: /tmp/bap-log
      OPAMJOBS: 2
      OPAMRETRES: 8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Pin BAP
        run: opam pin add bap . --no-action

      - name: Install system dependencies
        run: opam depext -u bap

      - name: Install conf-bap-llvm.master
        run: opam pin add conf-bap-llvm https://github.com/BinaryAnalysisPlatform/opam-repository/conf-bap-llvm/conf-bap-llvm.master

      - name: Install opam dependencies
        run: opam install bap --deps-only

      - name: Build and Install BAP
        run: opam install bap

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: opam-log
          path: ~/.opam/log
