name: Documentation

on:
  push:
    branches:
    - add-actions
#DON'T FORGET TO FIX BRANCH NAME AND ALSO README.md (badge)

jobs:
  update-docs:
     name: update-docs
     runs-on: self-hosted
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: building
         run: |
          docker image build .github/docker/docs -t docs
          docker run --rm docs ${{ secrets.MY_SECRET }}
#          docker image rm docs