name: Documentation

on:
  push:
    branches:
    - add-actions
#DON'T FORGET TO FIX BRANCH NAME AND ALSO READMEmd (badge)

jobs:
  my-job-name:
     name: Test
     runs-on: self-hosted
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: docker run
         run: |
          docker image build docker/docs -t docs
          docker run --rm -v `pwd`:/drive docs /drive
          docker image rm docs 
