name: Documentation

on:
  push:
    branches:
    - add-actions
#DON'T FORGET TO FIX BRANCH NAME AND ALSO README.md (badge)

jobs:
  update-docs:
     name: update-docs
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: building
         uses:  ./.github/actions/update-docs
         with:
           secret: ${{ secrets.MY_SECRET }}
