name: Publish Docker
on:
  - push


jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gitoleg/test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        tags: latest
