name: Publish Docker
on:
  - push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish docker image
      run: |
        docker build -t gitoleg/bap:latest docker/
        docker push gitoleg/bap:latest
        docker rm gitoleg/bap:latest
