name: Build documentation


on:
  - push
  #temp, replace to weekly later

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install system dependencies
      #   run: |
      #       opam pin add bap . -n
      #       opam depext bap --yes

      # - name: Install opam dependencies
      #   run: opam install . --deps-only

      # - name: Install BAP
      #   run: opam install bap --yes

      # - name: Build Documentation
      #   run: |
      #     sudo apt-get install emacs-nox man2html --yes
      #     opam install odig --yes
      #     make doc

      - name: Imitate docs
        run: |
          mkdir doc/man1
          mkdir doc/man3
          mkdir doc/lisp
          mkdir doc/odoc
          touch doc/man1/file1
          touch doc/man3/file2
          touch doc/lisp/file3
          touch doc/odoc/file4

      - name: Checkout blog
        uses: actions/checkout@v2
        with:
          repository: gitoleg/binaryanalysisplatform.github.io
          token: {{ secrets.MY_GHA_TOKEN }}
          path: blog

      - name: update and push
        run: |
          cp -r  doc/man1 blog/bap/api/
          cp -r  doc/man3 blog/bap/api/
          cp -r  doc/lisp blog/bap/api/
          cp -rL doc/odoc blog/bap/api/
          cd blog
          git add bap/api
          git commit -m "test message"
          git push origin master
