name: nightly-regression-tests

on:
  - push

jobs:
  build:
    strategy:
      matrix:
          os:
            - ubuntu-latest
            - macos-latest
          ocaml-version:
            - 4.07.1

    runs-on: ${{ matrix.os }}

    env:
      OPAMJOBS: 2
      OPAMRETRES: 8

    steps:
        - name: Use OCaml ${{ matrix.ocaml-version }}
          uses: avsm/setup-ocaml@v1
          with:
            ocaml-version: ${{ matrix.ocaml-version }}

        - name: Configure Homebrew
          if: matrix.os == 'macos-latest'
          run: |
            brew update
            brew upgrade
            echo '::set-env name=LLVM_CONFIG::/usr/local/opt/llvm@9/bin/llvm-config'

        - name: Add the Testing Repository
          run: opam repo add bap git://github.com/BinaryAnalysisPlatform/opam-repository#testing
        - name: Install System Dependencies
          run: opam depext -u bap

        - name: Cleanup the Caches
          if: matrix.os == 'ubuntu-latest'
          run: sudo apt clean --yes

        - name: Build and Install BAP
          run: opam install bap

        - name: Checkout the Tests
          uses: actions/checkout@v2
          with:
            submodules: true
            repository: gitoleg/bap
            ref: removes-symbol-info

        - name: Install Extra System Dependencies
          run: |
              opam pin add bap . -n
              opam depext -u bap

        - name: Run Functional Tests
          run: opam exec -- make check

        - uses: actions/upload-artifact@v2
          if: ${{ always() }}
          with:
            name: fun-tests-log-${{ matrix.os }}
            path: testsuite/times.log
