name: nightly-mac

on:
  - push
#  schedule:
#    - cron: '0 6 * * *' # Every day at 06:00 UTC, 2 am EDT

jobs:
  build:
    runs-on: macos-latest

    env:
      OPAMJOBS: 2
      OPAMRETRES: 8
      TMPDIR: /tmp
      XDG_CACHE_HOME: /tmp/cache
      BAP_LOG_DIR: /tmp/bap-log

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.09.1

      - name: Pin BAP
        run: opam pin add bap . --no-action

      - name: Configure Homebrew LLVM
        run: echo '::set-env name=LLVM_CONFIG::/usr/local/opt/llvm@9/bin/llvm-config'

      - name: Install system dependencies
        run: opam depext -u bap

      - name: Install opam dependencies
        run: opam install bap --deps-only

      - name: Build and Install BAP
        run: opam install bap
        #-v --with-test

     # - name: Run Functional Tests
     #   run: opam exec -- make check

      - name: Run BIL verification tool
        run: |
          git clone https://github.com/gitoleg/bap-veri
          opam pin add bap-veri bap-veri -n
          # opam pin add bap-veri testsuite/veri/bap-veri/ -n
          opam depext bap-veri
          opam install -v -v bap-veri
          opam exec -- make -C testsuite veri

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: bap-log
          path: ~/.local/state/bap

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: fun-tests-log
          path: testsuite/*.log