
name: release
on:
  - push
#  schedule:
#     - cron: '0 0 * * SAT' # every Saturday

jobs:
  build:
     runs-on: ubuntu-latest

     env:
       OPAMJOBS: 2
       OPAMRETRES: 8
       VERSION: 2.2.0

     steps:
         - name: Check repo tags
           run: |
             X=`git ls-remote --tags https://github.com/$GITHUB_REPOSITORY | grep v${{ env.VERSION }}`
             if [ "has$X" != "has" ]; then
                echo "the repository already has tag v${{ env.VERSION }}"
             fi


         - name: Checkout code
           uses: actions/checkout@v2
           with:
             submodules: recursive

         - name: Install OCaml
           uses: avsm/setup-ocaml@v1
           with:
             ocaml-version: 4.09.1+flambda

         - name: Build deb packages
           run: |
             ./tools/deb-build.sh ${{ env.VERSION }}

         - name: Get the previous pre-release
           id: get_prerelease
           uses: ./.github/actions/get-prerelease

         - name: Check the get-prelease action
           run: echo ${{ steps.get_prerelease.outputs.id }}

         - name: Delete previous prerelease
           if: steps.get_prerelease.outputs.id != ''
           uses: author/action-rollback@stable
           with:
             release_id: ${{ steps.get_prerelease.outputs.id }}
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - name: Create a new prerelease
           uses: "marvinpinto/action-automatic-releases@latest"
           with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: v${{ env.VERSION }}
             prerelease: true
             title: "Development Build"
             files: bap/*
