name: release
on:
  - push
#  schedule:
#     - cron: '0 0 * * SAT' # every Saturday

jobs:
  build:
     runs-on: ubuntu-latest

     env:
       OPAMJOBS: 2
       OPAMRETRES: 8
       VERSION: 2.2.0

     steps:
         - name: Checkout code
           uses: actions/checkout@v2
           with:
             submodules: recursive

         - name: Get the previous prerelease ID
           id: get_prerelease
           uses: ./.github/actions/get-prerelease

         - name: Delete the previous prerelease, if any
           if: steps.get_prerelease.outputs.id != ''
           uses: author/action-rollback@stable
           with:
             release_id: ${{ steps.get_prerelease.outputs.id }}
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

           # The action marvinpinto/action-automatic-releases below
           # will delete the tag if such one already exists. We need to
           # protect ourselves and don't let this happen.
         - name: Check if the tag is already exists
           run: |
             TAG=`git ls-remote --tags https://github.com/$GITHUB_REPOSITORY | grep v${{ env.VERSION }} || true`
             if [ "has$TAG" != "has" ]; then
                echo "The repository already has the tag v${{ env.VERSION }}"
                exit 1
             fi

         - name: Install OCaml
           uses: avsm/setup-ocaml@v1
           with:
             ocaml-version: 4.09.1+flambda

         - name: Build deb packages
           run: ./tools/deb-build.sh ${{ env.VERSION }}

         - name: Create a new prerelease
           uses: "marvinpinto/action-automatic-releases@latest"
           with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: v${{ env.VERSION }}
             prerelease: true
             title: "Development Build"
             files: bap/*
